db._useDatabase("Healthcare")

db.drug_matrix.drop()
db.similarity1.drop()
db.inv_norm.drop()
db.similarity2.drop()
db.drug_similarity.drop()

db._create("drug_matrix")
db._create("similarity1")
db._create("inv_norm")
db._create("similarity2")
db._create("drug_similarity")

db.drug_matrix.ensureIndex({type:"persistent", fields:["drug"]})
db.drug_matrix.ensureIndex({type:"persistent", fields:["adverse_effect"]})
db.similarity1.ensureIndex({type:"persistent", fields:["drug1"]})
db.similarity1.ensureIndex({type:"persistent", fields:["drug2"]})
db.inv_norm.ensureIndex({type:"persistent", fields:["drug1"]})
db.inv_norm.ensureIndex({type:"persistent", fields:["drug2"]})
db.similarity2.ensureIndex({type:"persistent", fields:["drug1"]})
db.similarity2.ensureIndex({type:"persistent", fields:["drug2"]})
db.drug_similarity.ensureIndex({type:"persistent", fields:["drug1"]})
db.drug_similarity.ensureIndex({type:"persistent", fields:["drug2"]})
